name: Release Branch Protection

on:
  pull_request:
    branches:
      - release

jobs:
  check-main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check for main branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != main ]];
          then
            echo "Error: Pull request must come from 'main' branch"
            exit 1
          fi
